# syntax=docker/dockerfile:1
ARG BASE_FINAL_IMAGE=alpine:3.20
######## Final Image  ########
FROM ${BASE_FINAL_IMAGE}
WORKDIR /app/
RUN apk --no-cache add curl lsof ca-certificates \
  && adduser -D nonpriv # create user and group
USER nonpriv
COPY myapp /app/myapp
CMD ["/app/myapp", "start"]
